package com.xeppaka.emi.events;

/**
 *
 */
public enum EmiEventType {
    PRODUCT_CREATED,
    PRODUCT_REMOVED,
    PRODUCT_NAME_CHANGED,
    PRODUCT_PRICE_CHANGED,
    CATEGORY_CREATED,
    CATEGORY_REMOVED,
    CATEGORY_NAME_CHANGED,
    CATEGORY_PARENT_CHANGED,
    CATEGORY_WEIGHT_CHANGED
}
