package com.xeppaka.emi.events;

/**
 *
 */
public enum EmiEventType {
    PRODUCT_CREATED,
    PRODUCT_DELETED,
    PRODUCT_NAME_CHANGED,
    PRODUCT_PRICE_CHANGED,
    PRODUCT_CATEGORY_CHANGED,
    PRODUCT_MULTIPLICITY_CHANGED,
    PRODUCT_FEATURES_CHANGED,
    PRODUCT_NOTE_CHANGED,
    PRODUCT_WEIGHT_CHANGED,
    CATEGORY_CREATED,
    CATEGORY_DELETED,
    CATEGORY_NAME_CHANGED,
    CATEGORY_PARENT_CHANGED,
    CATEGORY_WEIGHT_CHANGED
}
